SAVE

diff --git a/main/Makefile b/main/Makefile
--- a/main/Makefile
+++ b/main/Makefile
@@ -1,5 +1,8 @@
 NAME=minirt
 
+CC=gcc
+CFLAG=-Wall -Wextra -Werror
+
 # ---------- DIRCTORY ----------
 SRCS_DIR=srcs
 ORBJ_DIR=objs
@@ -31,13 +34,17 @@ LIBFT_DIR=zlib
 LIBFT_ARC=./$(LIBFT_DIR)/libft.a
 LIBFT=./$(LIBFT_DIR)/libft.a
 
+# ---- TEST RT FILES ----
+RT_DIR=scene
+TEST_RT=$(shell find ./$(RT_DIR) -name "error*" -type f 2> /dev/null)
+
 %.o: %.c
-	gcc -c $< -o $@ $(MLX_FLAGS)
+	$(CC) $(CFLAG) -c $< -o $@ $(MLX_FLAGS) -g
 
 all: $(NAME)
 
 $(NAME): $(OBJS) $(LIBFT)
-	gcc -Wall -Wextra -Werror $(OBJS) -o $(NAME) $(MLX_APATH) $(MLX_FLAGS) $(LIBFT_ARC)
+	$(CC) $(CFLAG) $(OBJS) -o $(NAME) $(MLX_APATH) $(MLX_FLAGS) $(LIBFT_ARC) -g
 
 $(LIBFT):
 	make -C zlib bonus
@@ -63,6 +70,34 @@ clean:
 valgrind: all
 	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./$(NAME) scene/test.rt
 
+# ALL BELOW case should exit with error status code != 0
+test: $(TEST_RT) all
+	@for item in $^ ; do \
+	if [ -f $$item ] ; then \
+		# echo "TEST file $$item  && ./$(NAME) $$item || echo $(GREEN)PASS$(RESET) && echo $(RED)FAIL$(RESET)"; \
+		echo -n "TEST file $$item \nresult:$(SEP2)" && ./$(NAME) $$item || echo "$(SEP2)$(GREEN)PASS$(RESET)\n" || echo "$(SEP2)$(RED)FAIL$(RESET)"; \
+		echo "$(SEPERATOR)" ;\
+	fi ;\
+	done ;\
+
+filename: all
+	@echo -n "TEST file temp \nresult:$(SEP2)" && ./$(NAME) temp || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo -n "$(SEPERATOR)"
+	@echo -n "TEST file .rt \nresult:$(SEP2)" && ./$(NAME) .rt || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo -n "$(SEPERATOR)"
+	@echo -n "TEST file rt \nresult:$(SEP2)" && ./$(NAME) rt || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo -n "$(SEPERATOR)"
+	@echo -n "TEST file r_t \nresult:$(SEP2)" && ./$(NAME) r_t || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo -n "$(SEPERATOR)"
+	@echo -n "TEST file plain.txt \nresult:$(SEP2)" && ./$(NAME) plain.txt || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo -n "$(SEPERATOR)"
+	@echo -n "TEST file not_exist.rt\nresult:$(SEP2)" && ./$(NAME) not_exist.rt || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo "$(SEPERATOR)"
+	@echo -n "TEST file 'aa bb' \nresult:$(SEP2)" && ./$(NAME) aa bb || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo "$(SEPERATOR)"
+	@echo -n "TEST file \nresult:$(SEP2)" && ./$(NAME)  || echo "$(SEP2)->$(GREEN)PASS$(RESET)" || echo "$(SEP2)->$(RED)FAIL$(RESET)"; 
+	@echo "$(SEPERATOR)"
+
 
 fclean: clean
 	make -C zlib fclean
@@ -70,4 +105,14 @@ fclean: clean
 
 re: fclean all
 
+# COLORS
+RED=\033[0;31m
+GREEN=\033[0;32m
+YELLOW=\033[0;33m
+BLUE=\033[0;34m
+MAGENTA=\033[0;35m
+CYAN=\033[0;36m
+RESET=\033[0m
+SEPERATOR=\n----------------------------------------\n
+SEP2=\n~~~~\n
 .PHONY: all clean fclean re mlxx libft
